add_rules("mode.debug", "mode.release")
set_languages("c++23")

add_requires("rapidjson", "fmt", "angelscript", "uuid_v4", "libpng", "spdlog", "simde")


target("AgeAPI")
    set_kind("static")
    add_files("AgeAPI/**.cpp")
    add_includedirs("AgeAPI/", {public = true})
    add_headerfiles("AgeAPI/**.hpp")
    add_packages("rapidjson", "fmt", "angelscript", "uuid_v4", "libpng", "spdlog", "AgeSharedUtils", {public = true})
    set_symbols("debug")

target("AgeRuntime")
    set_kind("binary")
    add_files("AgeRuntime/**.cpp")
    add_includedirs("AgeRuntime/", {public = false})
    add_headerfiles("AgeRuntime/**.hpp")
    add_deps("AgeAPI", "AgeSharedUtils")
    set_symbols("debug")

target("AgeCore")
    set_kind("shared")
    add_files("AgeCore/**.cpp")
    add_includedirs("AgeCore/", {public = false})
    add_headerfiles("AgeCore/**.hpp")
    add_deps("AgeAPI")
    set_symbols("debug")

target("AgeDataDumper")
    set_symbols("debug")
    set_kind("binary")
    add_files("AgeDataDumper/**.cpp")
    add_includedirs("AgeDataDumper/", {public = false})
    add_headerfiles("AgeDataDumper/**.hpp")
    add_packages("rapidjson", "fmt")
    
target("AgeDefaultDataCrawler")
    set_symbols("debug")
    set_kind("binary")
    add_files("AgeDefaultDataCrawler/**.cpp")
    add_includedirs("AgeDefaultDataCrawler/", {public = false})
    add_headerfiles("AgeDefaultDataCrawler/**.hpp")
    add_deps("AgeAPI", "AgeSharedUtils")
    add_packages("rapidjson", "fmt")

target("AgeSharedUtils")
    set_symbols("debug")
    set_kind("static")
    add_files("AgeSharedUtils/**.cpp")
    add_includedirs("AgeSharedUtils/", {public = true})
    add_headerfiles("AgeSharedUtils/**.hpp")
    add_packages("rapidjson", "simde", {public = true})

target("AgeTester")
    set_symbols("debug")
    set_kind("binary")
    add_files("AgeTester/**.cpp")
    add_includedirs("AgeTester/", {public = false})
    add_headerfiles("AgeTester/**.hpp")
    add_deps("AgeAPI", "AgeSharedUtils")
    add_arflags("somthing")